Domain/Controllers/AbsencesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HR_Task.Data;
using HR_Task.Models;
using NuGet.Common;

namespace HR_Task.Domain.Controllers
{
    public class AbsencesController : Controller
    {
        private readonly IAbsenceData _absenceData;
        private readonly IEmployeeData _employeeData;

        public AbsencesController(IAbsenceData absenceData,
            IEmployeeData employeeData)
        {
            _absenceData = absenceData;
            _employeeData = employeeData;
        }

        public async Task<IActionResult> Index(CancellationToken token)
        {
            return View(await _absenceData.GetAbsences(token));
        }

        public async Task<IActionResult> Details(int? id, CancellationToken token)
        {
            if (id == null)
            {
                return NotFound();
            }

            var absence = await _absenceData.GetAbsence(id.Value, token);

            if (absence == null)
            {
                return NotFound();
            }

            return View(absence);
        }

        public async Task<IActionResult> Create(CancellationToken token)
        {
            ViewData["EmployeeId"] = new SelectList(await _employeeData.GetEmployees(token), "Id", "FullName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EmployeeId,AbsenceDay")] Absence absence, CancellationToken token)
        {
            ModelState.Remove("employee");

            if (ModelState.IsValid)
            {
                await _absenceData.AddAbsence(absence, token);
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(await _employeeData.GetEmployees(token), "Id", "FullName");
            return View(absence);
        }

        // GET: Absences/Edit/5
        public async Task<IActionResult> Edit(int? id, CancellationToken token)
        {
            if (id == null)
            {
                return NotFound();
            }

            var absence = await _absenceData.GetAbsence(id.Value, token);
            if (absence == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(await _employeeData.GetEmployees(token), "Id", "FullName");
            return View(absence);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,EmployeeId,AbsenceDay")] Absence absence, CancellationToken token)
        {
            ModelState.Remove("employee");

            if (ModelState.IsValid)
            {
                var updatedU = await _absenceData.UpdateAbsences(absence, token);

                if (updatedU == null) return NotFound();

                return RedirectToAction(nameof(Details), new { id = updatedU.Id });
            }
            ViewData["EmployeeId"] = new SelectList(await _employeeData.GetEmployees(token), "Id", "FullName");
            return View(absence);
        }

    }
}

Domain/Controllers/BonusesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using HR_Task.Models;

namespace HR_Task.Domain.Controllers
{
    public class BonusesController : Controller
    {
        private readonly IBonusData _bonusData;
        private readonly IDepartmentData _departmentData;

        public BonusesController(IBonusData bonus,
            IDepartmentData departmentData)
        {
            _bonusData = bonus;
            _departmentData = departmentData;
        }

        public async Task<IActionResult> Index(CancellationToken token)
        {
            return View(await _bonusData.GetBonuses(token));
        }

        public async Task<IActionResult> Details(int? id, CancellationToken token)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bonus = await _bonusData.GetBonus(id.Value, token);

            if (bonus == null)
            {
                return NotFound();
            }

            return View(bonus);
        }

        public async Task<IActionResult> Create(CancellationToken token)
        {
            ViewData["TypeId"] = new SelectList(await _bonusData.GetBonusTypes(token), "Id", "Name");
            ViewData["Role"] = new SelectList(await _departmentData.GetDepartments(token), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TypeId,Rate,Role,RoleDepartment")] Bonus bonus, CancellationToken token)
        {
            ModelState.Remove("RoleDescreption");
            ModelState.Remove("BonusType");

            if (ModelState.IsValid)
            {
                await _bonusData.AddBonus(bonus, token);
                return RedirectToAction(nameof(Details), new { id = bonus.Id });
            }
            ViewData["TypeId"] = new SelectList(await _bonusData.GetBonusTypes(token), "Id", "Name");
            ViewData["Role"] = new SelectList(await _departmentData.GetDepartments(token), "Id", "Name");
            return View(bonus);
        }

        // GET: Bonuses/Edit/5
        public async Task<IActionResult> Edit(int? id, CancellationToken token)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bonus = await _bonusData.GetBonus(id.Value, token);

            if (bonus == null)
            {
                return NotFound();
            }
            ViewData["TypeId"] = new SelectList(await _bonusData.GetBonusTypes(token), "Id", "Name");
            ViewData["Role"] = new SelectList(await _departmentData.GetDepartments(token), "Id", "Name");
            return View(bonus);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,TypeId,Rate,Role")] Bonus bonus, CancellationToken token)
        {
            if (ModelState.IsValid)
            {
                var updatedBonus = await _bonusData.UpdateBonus(bonus, token);

                if (updatedBonus == null)
                {
                    return NotFound();
                }

                return RedirectToAction(nameof(Details), new { id = updatedBonus.Id });
            }

            ViewData["TypeId"] = new SelectList(await _bonusData.GetBonusTypes(token), "Id", "Name");
            ViewData["Role"] = new SelectList(await _departmentData.GetDepartments(token), "Id", "Name");
            return View(bonus);
        }
    }
}

Domain/Controllers/ReportsController.cs
using HR_Task.Models.Reporting;
using Microsoft.AspNetCore.Mvc;

namespace HR_Task.Domain.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IReportData _reportData;

        public ReportsController(IReportData reportData)
        {
            _reportData = reportData;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> SalaryReport(DateTime? fromDate, DateTime? toDate, CancellationToken token)
        {
            if (fromDate == null || toDate == null)
            {
                return View("SalaryReport", Array.Empty<EmployeesSalary>());
            }

            return View("SalaryReport", await _reportData.GetEmployeesSalaries(fromDate.Value, toDate.Value, token));
        }
    }
}

Domain/Controllers/SalariesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using HR_Task.Models;

namespace HR_Task.Domain.Controllers
{
    public class SalariesController : Controller
    {
        private readonly ISalaryData _salaryData;
        private readonly IJobRankData _jobRankData;
        private readonly IDepartmentData _departmentData;

        public SalariesController(ISalaryData salaryData,
            IJobRankData jobRankData,
            IDepartmentData departmentData)
        {
            _salaryData = salaryData;
            _jobRankData = jobRankData;
            _departmentData = departmentData;
        }

        public async Task<IActionResult> Index(CancellationToken token)
        {
            return View(await _salaryData.GetSalaries(token));
        }

        public async Task<IActionResult> Details(int? id, CancellationToken token)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _salaryData.GetSalary(id.Value, token);

            if (salary == null)
            {
                return NotFound();
            }

            return View(salary);
        }

        public async Task<IActionResult> Create(CancellationToken token)
        {
            ViewData["DepartmentId"] = new SelectList(await _departmentData.GetDepartments(token), "Id", "Name");
            ViewData["JobRankId"] = new SelectList(await _jobRankData.GetJobRanks(token), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Amount,DepartmentId,JobRankId")] Salary salary, CancellationToken token)
        {
            ModelState.Remove("Department");
            ModelState.Remove("JobRank");
            if (ModelState.IsValid)
            {
                var newSalary = await _salaryData.AddSalary(salary, token);

                return RedirectToAction(nameof(Details), new { id = newSalary.Id });
            }
            ViewData["DepartmentId"] = new SelectList(await _departmentData.GetDepartments(token), "Id", "Name");
            ViewData["JobRankId"] = new SelectList(await _jobRankData.GetJobRanks(token), "Id", "Name");

            return View(salary);
        }

        public async Task<IActionResult> Edit(int? id, CancellationToken token)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _salaryData.GetSalary(id.Value, token);

            if (salary == null)
            {
                return NotFound();
            }

            ViewData["DepartmentId"] = new SelectList(await _departmentData.GetDepartments(token), "Id", "Name");
            ViewData["JobRankId"] = new SelectList(await _jobRankData.GetJobRanks(token), "Id", "Name");

            return View(salary);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Amount,DepartmentId,JobRankId")] Salary salary, CancellationToken token)
        {
            ModelState.Remove("Department");
            ModelState.Remove("JobRank");
            if (ModelState.IsValid)
            {
                await _salaryData.UpdateSalary(salary, token);
                return RedirectToAction(nameof(Details), new { id = salary.Id });
            }
            ViewData["DepartmentId"] = new SelectList(await _departmentData.GetDepartments(token), "Id", "Name");
            ViewData["JobRankId"] = new SelectList(await _jobRankData.GetJobRanks(token), "Id", "Name");

            return View(salary);
        }
    }
}

Domain/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HR App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HR_Task.Domain.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HR_Task</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Salaries" asp-action="Index">Salaries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bonuses" asp-action="Index">Bonuses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AttendanceRoles" asp-action="Index">Attendance Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Absences" asp-action="Index">Absences</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Reports</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HR_Task.Domain - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>